from random import randint, choice, choices

region = {
    '01': 'Abşeron',
    '02': 'Ağdam',
    '03': 'Ağdaş',
    '04': 'Ağcabədi',
    '05': 'Ağstafa',
    '06': 'Ağsu',
    '07': 'Astara',
    '08': 'Balakən',
    '09': 'Bərdə',
    '10': 'Bakı',
    '11': 'Beyləqan',
    '12': 'Biləsuvar',
    '14': 'Cəbrayıl',
    '15': 'Cəlilabad',
    '16': 'Daşkəsən',
    '17': 'Dəvəçi',
    '18': 'Şirvan',
    '19': 'Füzuli',
    '20': 'Gəncə',
    '21': 'Gədəbəy',
    '22': 'Goranboy',
    '23': 'Göyçay',
    '24': 'Hacıqabul',
    '25': 'Xanlar',
    '26': 'Xankəndi',
    '27': 'Xaçmaz',
    '28': 'Xocavənd',
    '29': 'Xızı',
    '30': 'İmişli',
    '31': 'İsmayıllı',
    '32': 'Kəlbəcər',
    '33': 'Kürdəmir',
    '34': 'Qax',
    '35': 'Qazax',
    '36': 'Qəbələ',
    '37': 'Qobustan',
    '38': 'Qusar',
    '39': 'Qubadlı',
    '40': 'Quba',
    '41': 'Laçın',
    '42': 'Lənkəran',
    '43': 'Lerik',
    '44': 'Masallı',
    '45': 'Mingəçevir',
    '46': 'Naftalan',
    '47': 'Neftçala',
    '48': 'Oğuz',
    '49': 'Saatlı',
    '50': 'Sumqayıt',
    '51': 'Samux',
    '52': 'Salyan',
    '53': 'Siyəzən',
    '54': 'Sabirabad',
    '55': 'Şəki',
    '56': 'Şamaxı',
    '57': 'Şəmkir',
    '58': 'Şuşa',
    '59': 'Tərtər',
    '60': 'Tovuz',
    '61': 'Ucar',
    '62': 'Zaqatala',
    '63': 'Zərdab',
    '64': 'Zəngilan',
    '65': 'Yardımlı',
    '66': 'Yevlax',
    '67': 'Babək',
    '68': 'Şərur',
    '69': 'Ordubad',
    '70': 'Naxçıvan şəhəri',
    '71': 'Şahbuz',
    '72': 'Culfa',
    '77': 'Bakı',
    '85': 'Naxçıvan',
    '90': 'Bakı',
    '99': 'Bakı',
}

letters = 'ABCDEFGHJKLMNOPRSTUVXYZ'

prefix = choice(list(region))
series = ''.join(choices(letters, k=2))
numbers = f'{randint(1, 999)}'.zfill(3)

license_plate = '-'.join([prefix, series, numbers])
print('Region: {}'.format(region[prefix]))
print(license_plate) 